# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

# 忽略 pod 库警告
inhibit_all_warnings!
DEBUG_NO_LABKIT = 0
#############################################################
source 'https://github.com/CocoaPods/Specs.git'
source 'http://techgit.meitu.com/iosmodules/specs.git'
source 'http://techgit.meitu.com/iOSModules_public/specs.git'


target 'demoCrash' do

    # 微软崩溃工具
    pod 'KSCrash'

    # 微软崩溃工具
    pod 'PLCrashReporter'

    # 滴滴开源开发辅助工具DoKit WithMLeaksFinder
    pod 'DoraemonKit/Core'
    pod 'DoraemonKit/WithLoad'
    pod 'DoraemonKit/WithLogger'
    pod 'DoraemonKit/WithDatabase'
    pod 'DoraemonKit/WithMLeaksFinder'

    # Firebase统计
    pod 'Firebase', '6.15.0', :subspecs => ['Analytics', 'Crashlytics'],  :modular_headers => true
end

# 为解决模拟器环境本地库下.a编译报错：building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
# 模拟器编译排除arm64架构。build setting的设置会在pod install被覆盖，此处需要代码设置
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS"] = "armv7"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end

#target 'MTEveApp' do
#  pod 'Realm', '3.17.3', :modular_headers => true
#  pod 'RealmSwift'
#  pod 'Moya/RxSwift', '~> 11.0'
#  pod 'RxCocoa', '~> 4.1.0'
#  pod 'RxDataSources', '~> 3.1.0'
#  pod 'SDWebImage'
#  pod 'Yaml', '~> 3.4.3'
#  pod 'ReachabilitySwift'
#  pod 'ObjectMapper'
#  pod 'SSZipArchive', '~> 2.1.1'
#  pod 'SQLite.swift', '~> 0.11.5'
#  pod 'MJRefresh', '~> 3.1.15.3'
#  pod 'PGDatePicker'
#  pod 'lottie-ios'
#  pod 'QRCode', '~> 2.0'
#  pod 'UMCCommon'
#  pod 'UMCSecurityPlugins'
#  pod 'SnapKit', '~> 4.2'
#  pod 'QCloudCOSXML'
#  pod 'IQKeyboardManagerSwift'
#  pod 'Bugly
#end
